version: "3.6"
services:
  
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Documents/docker/portainer/data:/data
      - ~/Documents/docker/shared:/shared
    environment:
      - TZ="Europe/London"
